release-date = "2022-07-29"

[[entries]]
id = "fce0cf7b-aa28-4dd8-93be-95ad14feec89"
type = "feature"
description = "Define new interfaces for `Graph`, `GraphExecutor` and `GraphExecutorObserver` and provide default implementations that do not use termcolor, so we can get rid of that dependency in `kraken-core`"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/kraken-build/kraken-core/issues/3",
]
