release-date = "2022-08-12"

[[entries]]
id = "4e071b99-e3af-4f38-b3b2-a0af1aaf51ab"
type = "fix"
description = "No longer vendor `dill` package, if we try to use the vendored version we get weird pickle issues"
author = "@NiklasRosenstein"
