release-date = "2022-08-12"

[[entries]]
id = "5f0a1c70-cbae-4f65-ae49-1d1e377d0c6d"
type = "breaking change"
description = "remove unused `kraken.core.__main__`"
author = "@NiklasRosenstein"

[[entries]]
id = "ba132f16-6e48-4c6f-a01e-4c818f879d87"
type = "fix"
description = "fix `NameError` in `kraken query describe`"
author = "@NiklasRosenstein"
