[[entries]]
id = "41708edf-66dc-4686-8bdc-acc5640e6031"
type = "improvement"
description = "remove `--no-save` option from `kraken query` commands, the build state will never be saved after these commands"
author = "@NiklasRosenstein"
