[[entries]]
id = "f84793a2-2738-438f-b8c2-6003c32fce8b"
type = "feature"
description = "Introduce `Task.selected` attribute which is set to True when a task was explicitly selected in the CLI"
author = "@NiklasRosenstein"
