name: Python application

on:
  push: { branches: [ develop ], tags: [ "*" ] }
  pull_request: { branches: [ develop ] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]  # 3.11 can't be used because of Dill incompatibiltiy
    steps:
    - uses: actions/checkout@v2
    - uses: python-slap/slap.cli@gha/install/v1
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install -vv --no-venv-check
    - run: slap test

    # Test the example. Need docker for that.
    - uses: docker/setup-buildx-action@v2
    - run: cd example && kraken run build

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: python-slap/slap.cli@gha/install/v1
    - run: slap venv -ac && slap install --only-extras docs
    - run: slap run docs:build
    - uses: actions/upload-artifact@v2
      with: { name: docs, path: docs/_site }
    - uses: Cecilapp/GitHub-Pages-deploy@v3
      env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
      with: { email: rosensteinniklas@gmail.com, build_dir: docs/_site }
      if: ${{ github.ref == 'refs/heads/develop' }}
